version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  ingestion:
    build: ./ingestion
    depends_on:
      - postgres

volumes:
  postgres_data: